### PR TITLE
Improved layout and added resource

### PR DESCRIPTION
**Pull request by onlyasmalllizard**
- Made nav bar and footer stick to the top and bottom respectively
- Moved background colour to the body instead of container so that there would not be a colour change on pages with less content
- Made lists on resource page line up with each other vertically
- Added App Academy to resources

### CODE REVIEW

**Comment by yamiacat** [comment]
Hullo Lizard! It looks like you've added the whole navbar and footer to every page separately? That shouldn't be necessary as Jekyll takes care of that for us. (Although unfortunately we haven't got the README to an advanced enough state where it explains it well.)

Can you remove those changes? Sorry to be a pain! The other stuff looks good though!

**Comment by onlyasmalllizard** [comment]
That's weird, I didn't think I did that! I was mainly working with the .css file. I'll try and figure out what happened.

**Comment by onlyasmalllizard** [comment]
I have a theory about why it looks like I inserted them manually. I did change the default layout page so that the nav bar and footer were in a separate container from the content. The formatting just wasn't working properly until I split them out. Would that have made it look like they were inserted manually into the rest of the pages?

**Comment by yamiacat** [comment]
Hmmm, you may have generated the site with jekyll and then committed the generated version - that would explain it!

I notice there's also a jekyll cache folder added, which we also wouldn't want - I think that would have to be added to the .gitignore

**Comment by yamiacat** [comment]
I'm just working with Joy who is also using Jekyll to generate a preview version, and we've had to add this to the .gitignore:

https://github.com/enjoy15/OpenCodeClub.github.io/blob/30280851c0f90215b40a2279977d358741b0b37f/.gitignore#L39-L44

**Comment by onlyasmalllizard** [comment]
Thank you for your help on this! I updated my version, but when I went to pull again, it said they were identical, so we must have done the same thing on either end!

**Comment by yamiacat** [comment]
I think we've made the same changed to the .gitignore, yes!

You might want to make a back up of what you've done, then close this PR, then pull in the latest upstream version, then open 2 separate PRs, one for the changes to the Resources page, the other for the background colour? How does that sound?

**Comment by onlyasmalllizard** [comment]
I'll have a go!

**Pull request closed without merging**
